data:extend({
    --[[ memes ]] --
    -- subgroup
    {
        type = "item-subgroup",
        name = "virtual-signal-galore-memes",
        group = "signals",
        order = "zzz-signal-galore-a",
    },
    -- signals
    {
        type = "virtual-signal",
        name = "signal-dickbutt",
        icon = "__signals-galore__/graphics/icons/signal/memes/dickbutt.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-memes",
    },
    {
        type = "virtual-signal",
        name = "signal-pepe-sad",
        icon = "__signals-galore__/graphics/icons/signal/memes/pepe-sad.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-memes",
    },
    {
        type = "virtual-signal",
        name = "signal-doge",
        icon = "__signals-galore__/graphics/icons/signal/memes/doge.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-memes",
    },
    --[[ greek ]] --
    -- subgroup
    {
        type = "item-subgroup",
        name = "virtual-signal-galore-greek",
        group = "signals",
        order = "zzz-signal-galore-b",
    },
    -- signals
    {
        type = "virtual-signal",
        name = "signal-greek-alpha",
        icon = "__signals-galore__/graphics/icons/signal/greek/alpha.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-ba",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-beta",
        icon = "__signals-galore__/graphics/icons/signal/greek/beta.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bb",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-gamma",
        icon = "__signals-galore__/graphics/icons/signal/greek/gamma.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bc",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-delta",
        icon = "__signals-galore__/graphics/icons/signal/greek/delta.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bda",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-delta-2",
        icon = "__signals-galore__/graphics/icons/signal/greek/delta-2.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bdb",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-epsilon",
        icon = "__signals-galore__/graphics/icons/signal/greek/epsilon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-be",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-zeta",
        icon = "__signals-galore__/graphics/icons/signal/greek/zeta.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bf",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-eta",
        icon = "__signals-galore__/graphics/icons/signal/greek/eta.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bg",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-theta",
        icon = "__signals-galore__/graphics/icons/signal/greek/theta.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bh",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-iota",
        icon = "__signals-galore__/graphics/icons/signal/greek/iota.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bi",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-kappa",
        icon = "__signals-galore__/graphics/icons/signal/greek/kappa.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bj",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-lambda",
        icon = "__signals-galore__/graphics/icons/signal/greek/lambda.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bk",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-mu",
        icon = "__signals-galore__/graphics/icons/signal/greek/mu.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bl",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-nu",
        icon = "__signals-galore__/graphics/icons/signal/greek/nu.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bm",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-xi",
        icon = "__signals-galore__/graphics/icons/signal/greek/xi.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bn",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-pi",
        icon = "__signals-galore__/graphics/icons/signal/greek/pi.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bo",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-sigma",
        icon = "__signals-galore__/graphics/icons/signal/greek/sigma.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bp",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-tau",
        icon = "__signals-galore__/graphics/icons/signal/greek/tau.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bq",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-upsilon",
        icon = "__signals-galore__/graphics/icons/signal/greek/upsilon.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-br",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-phi",
        icon = "__signals-galore__/graphics/icons/signal/greek/phi.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bs",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-chi",
        icon = "__signals-galore__/graphics/icons/signal/greek/chi.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bt",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-psi",
        icon = "__signals-galore__/graphics/icons/signal/greek/psi.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bu",
    },
    {
        type = "virtual-signal",
        name = "signal-greek-omega",
        icon = "__signals-galore__/graphics/icons/signal/greek/omega.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-greek",
        order = "zzz-signal-galore-bv",
    },
    --[[ emojis ]] --
    -- subgroup
    {
        type = "item-subgroup",
        name = "virtual-signal-galore-emojis",
        group = "signals",
        order = "zzz-signal-galore-c",
    },
    -- signals
    {
        type = "virtual-signal",
        name = "signal-fish",
        icon = "__signals-galore__/graphics/icons/signal/emojis/fish.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-gorilla",
        icon = "__signals-galore__/graphics/icons/signal/emojis/gorilla.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-factory",
        icon = "__signals-galore__/graphics/icons/signal/emojis/factory.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-floppy_disk",
        icon = "__signals-galore__/graphics/icons/signal/emojis/floppy_disk.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-radioactive",
        icon = "__signals-galore__/graphics/icons/signal/emojis/radioactive.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-rocket",
        icon = "__signals-galore__/graphics/icons/signal/emojis/rocket.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-roll_paper",
        icon = "__signals-galore__/graphics/icons/signal/emojis/roll_paper.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-scroll",
        icon = "__signals-galore__/graphics/icons/signal/emojis/scroll.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-sunflower",
        icon = "__signals-galore__/graphics/icons/signal/emojis/sunflower.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
    {
        type = "virtual-signal",
        name = "signal-toilet",
        icon = "__signals-galore__/graphics/icons/signal/emojis/toilet.png",
        icon_size = 64, icon_mipmaps = 1,
        subgroup = "virtual-signal-galore-emojis",
    },
})
